---
_resource_selection:
  distribution: "{{ ansible_distribution + ansible_distribution_version }}"
  architecture: "{{ ansible_machine }}"
  environment:

# Resource repository keys.
_resource_repository_keys:
  - architecture:
    - x86_64:
      - common:
        - "https://package.perforce.com/perforce.pubkey"

resource_repository_keys: "\
  {{ _resource_repository_keys | select_install(_resource_selection) }}"

# Resource repositories.
_resource_repositories:
  - common:
    - name: pbit-uds-devel
      description: Permabit UDS development packages
      enabled: yes
      gpgcheck: no
      sslverify: no
      baseurl: "http://vdo-image-store.permabit.lab.eng.bos.redhat.com/uds-devel-repo/SRPMs"

  - architecture:
    - x86_64:
      - common:
        # N.B.: The perforce.com instructions for RHEL families say to use
        # http:// for this, but their web server rejects connections with a
        # User-Agent of "dnf", which will be an issue for Fedora support. Using
        # https:// gets the data, and bypasses the problem on their end.
        - name: perforce
          description: Perforce
          enabled: yes
          gpgcheck: yes
          sslverify: no
          baseurl: "
            {%- if is_rhel8_or_later_family -%}
              https://package.perforce.com/yum/rhel/8/x86_64/
            {%- else -%}
              https://package.perforce.com/yum/rhel/7/x86_64/
            {%- endif -%}"

resource_repositories: "\
  {{ _resource_repositories | select_install(_resource_selection) }}"

# Resource packages.
_packages:
  # Common to all distributions.
  - common:
    # These packages are not available in RHEL 7.5 family, but ARE available
    # in FC27
    #- perl-Graph
    #- perl-Net-Ping
    #- perl-PDF-Create
    #- perl-Perl-Critic-Deprecated
    #- perl-bignum
    #- python-werkzeug
    - autoconf
    - device-mapper-event
    - device-mapper-event-devel
    - doxygen
    - dwarves
    - elfutils
    - elfutils-libelf-devel
    - gcc
    - gdb
    - libaio-devel
    - libuuid
    - libuuid-devel
    - redhat-rpm-config
    - rpm-build
    - texlive
    - texlive-collection-latex
    - texlive-collection-latexrecommended
    - texlive-latex
    - texlive-latex-bin
    - texlive-latex-bin-bin
    - texlive-latex-fonts
    - texlive-latexconfig
    - texlive-lualatex-math
    - texlive-metafont-bin
    - texlive-multirow
    - texlive-pslatex
    - texlive-sectsty
    - texlive-tocloft
    - texlive-xtab
    - valgrind
    - valgrind-devel

  # N.B.: The yumdownloader program is needed by the permabuild_builder
  # role. It used to be provided by yum-utils, but that was replaced by
  # dnf-utils. In some distros (RHEL 8 family, Fedora 31), they're aliased,
  # but Fedora 29 and 30 have both, and RHEL 7 family doesn't know about dnf.
  #  On some of our systems, a preinstalled package "beakerlib" depends on
  # these tools, too.
  #
  # We have to use yum-utils on RHEL 7 family, because it doesn't know the name
  # dnf-utils. We have to use dnf-utils on Fedora 29/30, because that's what
  # beakerlib (1.18-6) uses. Distro with the aliases won't care.

  ##########################################################################
  # Fedora
  ##########################################################################
  # Common to all Fedora starting with Fedora28.
  - Fedora([1-9][0-9]{2,}|2[8-9]|[3-9][0-9]):
    - dnf-utils
    - fping
    - sshpass

  # Common to all Fedora starting with Fedora28 until Fedora33.
  - Fedora(2[8-9]|3[0-3]):
    - texlive-texconfig

  ##########################################################################
  # RHEL families
  ##########################################################################
  # Common to all RHEL families starting with RHEL 7.5
  - (CentOS|RedHat)([1-9][0-9]+\.[0-9]+|([7-9])\.([1-9][0-9]+)|7\.[5-9]|[8-9]\.[0-9]):
    - texlive-texconfig

  # Common to all RHEL 7 family starting with RHEL 7.5 family.
  - (CentOS|RedHat)7\.([1-9][0-9]+|[5-9]):
    - fping
    - sshpass
    - yum-utils

  # Common to all RHEL families starting with RHEL 8.0 family.
  - (CentOS|RedHat)(?![1-7]\.[0-9]+)[1-9][0-9]*\.[0-9]+:
    - device-mapper-devel
    - dnf-utils

  ##########################################################################
  # Architecture-specific.
  ##########################################################################
  - architecture:
    - aarch64:
    - ppc64le:
    - s390x:
    - x86_64:
      - Fedora([1-9][0-9]{2,}|2[8-9]|[3-9][0-9]):
        - coccinelle
        - ctags
        - p4perl

      - (CentOS|RedHat)(7|8)\.[0-9]+:
        - coccinelle
        - ctags
        - p4perl

      - common:
        - id-utils

resource_base_packages: "{{ _packages | select_install(_resource_selection) }}"

resource_perforce_packages:
  - helix-cli

# Perl modules to install, either as RPMs or from CPAN.
#
# N.B. The modules are specified based on order dependence.
_perl_libraries:
  # Common to all RHEL families starting with RHEL 7.5 family.
  - (CentOS|RedHat)([1-9][0-9]+\.[0-9]+|([7-9])\.([1-9][0-9]+)|7\.[5-9]|[8-9]\.[0-9]):
    - File::ShareDir
    - File::Share
    - Graph::Directed
    - PDF::Create
    - String::ShellQuote

  # Common to all.
  - common:
    - Net::Ping
    - Sys::CpuLoad

perl_libraries: "{{ _perl_libraries | select_install(_resource_selection) }}"
