---
_resource_selection:
  distribution: "{{ ansible_distribution + ansible_distribution_version }}"
  architecture: "{{ ansible_machine }}"
  environment:

# Resource packages.
_packages:
  # Common to all distributions.
  - common:
    # These packages are not available in RHEL 7.5 family, but ARE available
    # in FC27
    #- perl-Graph
    #- perl-Net-Ping
    #- perl-PDF-Create
    #- perl-Perl-Critic-Deprecated
    #- perl-bignum
    #- python-werkzeug
    - autoconf
    - device-mapper-event
    - device-mapper-event-devel
    - doxygen
    - dwarves
    - elfutils
    - elfutils-libelf-devel
    - gcc
    - gdb
    - libaio-devel
    - libuuid
    - libuuid-devel
    # These perl-Permabit-* packages are needed to build and run tests of the
    # VDO tree.
    - perl-Permabit-Propertied
    - perl-Permabit-TestRunner
    - redhat-rpm-config
    - rpm-build
    - texlive
    - texlive-collection-latex
    - texlive-collection-latexrecommended
    - texlive-latex
    - texlive-latex-bin
    - texlive-latex-bin-bin
    - texlive-latex-fonts
    - texlive-latexconfig
    - texlive-lualatex-math
    - texlive-metafont-bin
    - texlive-multirow
    - texlive-pslatex
    - texlive-sectsty
    - texlive-tocloft
    - texlive-xtab
    - valgrind
    - valgrind-devel

  ##########################################################################
  # Fedora
  ##########################################################################
  # Common to all Fedora starting with Fedora28.
  - Fedora([1-9][0-9]{2,}|2[8-9]|[3-9][0-9]):
    - fping
    - sshpass

  # Common to all Fedora starting with Fedora28 until Fedora33.
  - Fedora(2[8-9]|3[0-3]):
    - texlive-texconfig

  ##########################################################################
  # RHEL families
  ##########################################################################
  # Common to all RHEL families starting with RHEL 7.5
  - (CentOS|RedHat)([1-9][0-9]+\.[0-9]+|([7-9])\.([1-9][0-9]+)|7\.[5-9]|[8-9]\.[0-9]):
    - texlive-texconfig

  # Common to all RHEL 7 family starting with RHEL 7.5 family.
  - (CentOS|RedHat)7\.([1-9][0-9]+|[5-9]):
    - fping
    - sshpass

  # Common to all RHEL families starting with RHEL 8.0 family.
  - (CentOS|RedHat)(?![1-7]\.[0-9]+)[1-9][0-9]*\.[0-9]+:
    - device-mapper-devel

  ##########################################################################
  # Architecture-specific.
  ##########################################################################
  - architecture:
    - aarch64:
    - ppc64le:
    - s390x:
    - x86_64:
      - Fedora([1-9][0-9]{2,}|2[8-9]|[3-9][0-9]):
        - coccinelle
        - ctags

      - (CentOS|RedHat)(7|8)\.[0-9]+:
        - coccinelle
        - ctags

resource_base_packages: "{{ _packages | select_install(_resource_selection) }}"

# Perl modules to install, either as RPMs or from CPAN.
#
# N.B. The modules are specified based on order dependence.
_perl_libraries:
  # Common to all RHEL families starting with RHEL 7.5 family.
  - (CentOS|RedHat)([1-9][0-9]+\.[0-9]+|([7-9])\.([1-9][0-9]+)|7\.[5-9]|[8-9]\.[0-9]):
    - File::ShareDir
    - File::Share
    - Graph::Directed
    - PDF::Create
    - String::ShellQuote

  # Common to all.
  - common:
    - Net::Ping
    - Sys::CpuLoad

perl_libraries: "{{ _perl_libraries | select_install(_resource_selection) }}"
