#!/bin/sh
# Helper script to automatically supply the required arguments and run the
# normal playbook.
#
# Limit arguments (-l) may still be supplied.

# Vagrant's normal invocation is to supply the directory name, which tells
# Ansible to pick up all files in that directory.
INVENTORY=.vagrant/provisioners/ansible/inventory/
INVENTORY_FILE=$INVENTORY/vagrant_ansible_inventory
# Check explicitly, as Ansible will continue with an empty list!
if ! [ -r $INVENTORY_FILE ]; then
    echo Inventory file $INVENTORY_FILE not found 1>&2
    exit 1
fi

exec ansible-playbook \
  --ssh-common-args="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
  -b -i $INVENTORY "$@" provisioning/playbook.yml
