---
- name: Install the host required bunsen python packages
  shell: pip{{ pip_version }} install
            --upgrade --trusted-host {{extra_host["name"]}}
            --extra-index-url {{extra_host["schema"]}}{{extra_host["name"]}}{{extra_host["path"]}}
            {{ packages | join(" ") }}
  vars:
    extra_host: "{{ externals['bunsen']['python-packages']['host'] }}"
    extra_host_path: "{{ externals['bunsen']['python-packages']['host']['name']['path'] }}"
    pip_version: "{{ ((ansible_python_major | int) == 2) | ternary('', ansible_python_major) }}"
    packages: ["python-distributions"]
