---
- name: Get host ansible_python_interpreter version
  command: "{{ansible_python_interpreter}} --version"
  register: result

- name: Record the host ansible_python_interpreter major version
  set_fact:
    ansible_python_major: "{{result.stdout.split()[1].split('.')[0]}}"

- name: Retrieve get-pip.py
  uri:
    url: "{{pip['schema']}}{{pip['name']}}{{pip['path']}}"
    dest: /tmp/get-pip.py
    creates: /tmp/get-pip.py
    mode: 0755
  vars:
    pip_key: "{{['pip', ansible_python_major] | join}}"
    pip: "{{externals['bunsen'][pip_key]['host']}}"

- name: Install pip using the host ansible_python_interpreter
  command: "{{ansible_python_interpreter}} /tmp/get-pip.py"
