---
- name: Create 'rsvpclient' symlink
  file:
    src: /permabit/build/perl/lastrun/bin/rsvpclient.pl
    dest: /usr/bin/rsvpclient
    state: link

# XX These are only helpful for interactive shells, but not inetd/cron
# jobs like "athinfo...checkserver".  Additional heuristics could work
# with a vagrant config.
# RSVP needs to grow a config file.
- name: RSVP server selection (csh)
  template:
    src: rsvp.csh
    dest: /etc/profile.d/rsvp.csh
    mode: 0644

- name: RSVP server selection (sh)
  template:
    src: rsvp.sh
    dest: /etc/profile.d/rsvp.sh
    mode: 0644
