---
#
# Install SSH key from /permabit/ops/ssh/hostkeys so we have the
# same across all pfarms. Private keys are in gpg format in the source
# and need to be decrypted first. Once we get the keys in the proper format,
# make sure permissions are set properly.
#
- block:
  - block:
    - name: List all keys
      find:
        paths: /permabit/ops/ssh/hostkeys/pfarm/
        file_type: file
        recurse: no
      register: sshKeyFiles

    - name: Copy files
      copy:
        src: "{{ item }}"
        dest: /etc/ssh
        mode: 0644
      with_items: "{{ sshKeyFiles.files | map(attribute='path') | list  }}"

  - block:
    - name: List GPG files
      find:
        paths: "/etc/ssh"
        file_type: file
        recurse: no
        patterns: '*.gpg'
      register: gpgFiles

    - name: Decrypt Files
      shell: echo {{ gpgkey }} |
             gpg --batch -q --homedir /tmp --yes --passphrase-fd 0 \
             --no-tty --ignore-mdc-error {{ item }}
      with_items: "{{ gpgFiles.files | map(attribute='path') | list  }}"
      vars:
        gpgkey: palduic
    tags: decryptGPG

  - block:
    - name: Find key files
      find:
        paths: "/etc/ssh"
        file_type: file
        recurse: no
        patterns: '*_key'
      register: keyFiles

    - name: Fix private key files permission
      file:
        path: "{{ item }}"
        mode: 0600
      with_items: "{{ keyFiles.files | map(attribute='path') | list  }}"

  when:  (is_pfarm | bool)
