---
# Configure athinfo
- name: Create /etc/athena directory
  file:
    path: /etc/athena
    owner: root
    group: root
    mode: 0755
    state: directory
# The man page says this directory need not exist, but the daemon
# reports an error if it doesn't.
- name: Create /etc/athena/athinfo.defs.d directory
  file:
    path: /etc/athena/athinfo.defs.d
    owner: root
    group: root
    mode: 0755
    state: directory
- name: Install athinfo.access
  copy:
    dest: /etc/athena/athinfo.access
    owner: root
    group: root
    mode: 0644
    content: "enable *"
- name: Install athinfo.defs
  copy:
    dest: /etc/athena/athinfo.defs
    owner: root
    group: root
    mode: 0644
    src: athinfo.defs
- name: Remove /etc/athinfo
  file:
    path: /etc/athinfo
    state: absent
- name: Link /etc/athinfo to /etc/athena
  file:
    src: /etc/athena
    dest: /etc/athinfo
    state: link
    force: yes

- block:
  - name: Add athinfo/tcp to /etc/services
    lineinfile:
      path: /etc/services
      line: "athinfo 49155/tcp"
  - name: Install athinfo xinetd specification
    template:
      src: athinfo.xinetd
      dest: /etc/xinetd.d/athinfo
      owner: root
      group: root
      mode: 0644
  when: system_has_xinetd | bool

# Setup systemd service file for athinfod
- block:
  - name: Copy athinfd.socket file
    copy:
      src: athinfod.socket
      dest: /etc/systemd/system/athinfod.socket
      owner: root
      group: root
      mode: 0644
  - name: Install athinfod@.service
    template:
      src: athinfod.service
      dest: /etc/systemd/system/athinfod@.service
      owner: root
      group: root
      mode: 0644
  when: (not (system_has_xinetd | bool))
