---
- block:
  - name: Clone required git repos.
    become: yes
    git:
      repo: "{{ item['url'] }}"
      dest: "{{ item['dest_dir'] }}/{{ item['name'] }}"
      clone: yes
      depth: 1
    register: result
    until: result is success
    retries: "{{ default_retry_count }}"
    delay: "{{ default_retry_delay }}"
    with_items: "{{ git_repos }}"

  - name: Install required git repos.
    become: yes
    shell: |
      cd "{{ item['dest_dir'] }}/{{ item['name'] }}" &&
      {{ item['install'] | default("echo -n") }}
    with_items: "{{ git_repos }}"
