---
# Adds aliases for perforce server in /etc/hosts when not a pfarm and is
# a system on which the p4 command line utility is installed (x86-only).
- name: Add perforce host aliases in /etc/hosts
  vars:
    ipaddr: 10.19.117.7
  lineinfile:
    dest: /etc/hosts
    regexp: '^{{ ipaddr }}\s+
              pbitperforce01.permabit.lab.eng.bos.redhat.com\s+
              pbitperforce01\s+pbitperforce\s+perforce$'
    line: '{{ ipaddr }} 
            pbitperforce01.permabit.lab.eng.bos.redhat.com
            pbitperforce01 pbitperforce perforce' 
    state: present
  become: yes    
  when: (not (is_pfarm | bool)) and (is_family_x86 | bool)
