---
- name: Update journald.conf
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: "{{ item.pattern }}"
    line: "{{ item.line }}"
  with_items:
    - { pattern: "RateLimitIntervalSec=", line: "RateLimitIntervalSec=0s" }
    - { pattern: "Storage=",              line: "Storage=persistent" }
  register: journald_config

- name: Ensure persistent journal directory exists
  file:
    path: /var/log/journal
    state: directory
  register: journal_dir

- name: Fix persistent journal directory permissions
  command: "systemd-tmpfiles --create --prefix /var/log/journal"

- name: Flush journal
  command: "journalctl --flush"
  when: journal_dir is changed

- name: Reload journald configuration
  systemd:
    name: systemd-journald
    state: restarted
  when: journald_config is changed or journal_dir is changed
