---
- include: release_config_dir.yml

# Do this after the reboot that ensures that crashkernel memory has been
# reserved.
- name: Enabling kdump service
  systemd:
    name: kdump.service
    state: started
    enabled: True
  # See above re: zipl boot loader.
  when: is_fedora and (not is_arch_s390x)
  become: yes

- name: Enable use of /proc/sysrq-trigger
  sysctl:
    name: kernel.sysrq
    value: "1"
    sysctl_set: yes
  become: yes

- name: Enable crash dump on NMI
  sysctl:
    name: "{{ item }}"
    value: "1"
    sysctl_set: yes
  with_items:
    - kernel.panic_on_unrecovered_nmi
    - kernel.unknown_nmi_panic
  when: is_vagrant | bool
  become: yes

- name: Enable core dump generation
  lineinfile:
    path: /etc/systemd/system.conf
    regexp: "^DefaultLimitCORE="
    state: present
    line: "DefaultLimitCORE=0:infinity"
  register: systemd_config
  become: yes

- name: Restart systemd and sshd to use new core dump setting
  systemd:
    name: sshd
    daemon_reexec: yes
    state: restarted
  when: systemd_config is changed
  become: yes

- name: Enable sysstat monitoring
  systemd:
    name: sysstat
    state: started
    enabled: yes
  become: yes

- name: Ensure distro VDO package lock directory is not present
  file:
    path: /var/lock/vdo
    state: absent
  become: yes
