---
- name: Register with the RSVP server
  vars:
    farm: "{{ inventory_hostname }}"
    os_class: "
      {%- set distribution = ansible_distribution | upper -%}
      {%- if distribution == 'REDHAT' -%}
        RHEL{{ ansible_distribution_major_version }}
      {%- else -%}
        {{ distribution }}{{ ansible_distribution_major_version }}
      {%- endif -%}"
    classes:
      - 64BITOK
      - ALBIREO
      - ALL
      # pfarms are not (at present) considered farms for purposes of testing.
      - "{{ (is_pfarm | bool) | ternary(omit, 'FARM') }}"
      - VDO
      # According to checkServer.pl, only virtual machines should be in class
      # VFARM, but basically all our tests require VFARM, so we need all Beaker
      # systems to wind up in VFARM until that gets fixed.
      - VFARM
      - "{{ (ansible_memtotal_mb > bigmem_mb) | ternary('BIGMEM', omit) }}"
      - "{{ os_class }}"
      - "{{ is_fedora | bool | ternary('FEDORA', omit) }}"
      - "{{ ((is_fedora | bool) or (is_rhel8_family | bool))
            | ternary('LINUX-UDS', omit) }}"
      - "{{ ((is_fedora | bool) or (is_rhel8_family | bool))
            | ternary('LINUX-VDO', omit) }}"
      - "{{ (ansible_virtualization_role == 'guest')
            | ternary(omit, 'NTP') }}"
      - "{{ (inventory_hostname in performance_farms)
            | ternary('VDO-PMI', omit) }}"
      - "{{ (ansible_virtualization_role == 'guest'
             and ansible_virtualization_type == 'kvm')
            | ternary('KVM', omit) }}"
    # For convenience above, we want to support something like the "omit"
    # construct, but it doesn't work in simple list contexts; "omit" just
    # expands to some magic cookie value which we still have to explicitly
    # filter out.
    class_list: "{{ classes | difference(omit) | join(',') }}"
    bigmem_mb: 16384
  command: "rsvpclient --dhost {{ rsvp_server }} add {{ farm }} \
            --classes {{ class_list }}"
  become: yes
  become_user: "{{ master_user }}"
  register: result
  failed_when:
    - result.rc != 0
    - not (result.stderr is search(inventory_hostname ~ '.* already exists'))
    - not (result.stderr is search(hostvars[inventory_hostname].ansible_fqdn ~ '.* already exists'))
  changed_when: result.rc == 0
  when: not is_pfarm

  # TODO: get the classes from the server.
  #       The list_classes --csv output is as:
  #         ALL,Default Class,class
  #         FARM,Default reservation class,class
  #         RHEL7, ,class
  #         VDO, ,class
  #         VFARM, ,class


