---
- block:
  - name: Restart crond (workaround for Fedora)
    service:
      name: crond
      state: restarted
    when: is_fedora

  - name: Start and enable xinetd service
    systemd:
      name: xinetd
      state: restarted
      enabled: yes
    when: system_has_xinetd | bool

  - name: Start and enable athinfod.socket
    systemd:
      name: athinfod.socket
      state: started
      enabled: True
    when: (not (system_has_xinetd | bool))

  - name: Make sure dkms is enabled
    systemd:
      name: dkms
      state: started
      enabled: True
