# This is the playbook for provisioning a testing virtual environment.
- hosts: all
  roles: 
    - postInstall

  post_tasks:
    - name: Check if bunsen log exists
      stat:
        path: /var/log/bunsen.log
      register: bunsen_log

    - name: Check if this is the first install attempt
      lineinfile:
        path: /var/log/bunsen.log
        line: "Install Date: N/A"
        state: present
      check_mode: yes
      register: first
      when: bunsen_log.stat.exists == true

    - name: Update bunsen log with successful install date/time
      vars:
        install_date_time:
          "{{ '%Y%m%d_%H%M%S' | strftime(ansible_date_time.epoch) }}"
      lineinfile:
        path: /var/log/bunsen.log
        regexp: '^Install Date:'
        line: 'Install Date: {{ install_date_time }}'
      when: first is not skipped 
