---
- include: make_known.yml
# Make certain we're known by our FQDN.
- include_tasks: make_known.yml
  vars:
    host: "{{ hostvars[inventory_hostname].ansible_fqdn }}"
- include_tasks: make_known.yml
  vars:
    host: "{{ ansible_controller_ip }}"
  when: is_devvm | bool
