---
# The externals file is generally organized as a dictionary of dictionaries of
# arbitrary depth.

# The various software required for bunsen's internal functionality as well as
# those bunsen will install on target machines during provisioning.
_distro_releasever: "{{ansible_distribution | lower | replace('redhat', 'rhel', 1)}}-{{is_fedora | ternary('$releasever', target_distribution_major_number)}}"
externals:
  # Resources for bunsen functionality.
  bunsen:
    python-support:
      schema: rpm
      host:
        schema: http://
        name: coprbe.devel.redhat.com
        path: "/results/jshimkus/python-support/{{_distro_releasever}}-$basearch"
        keypath: /results/jshimkus/python-support/pubkey.gpg

  # Resources provided by the group.
  first-party:
    file-server:
      schema: rpm
      host:
        schema: http://
        name: file.rdu.redhat.com
        path: /~awalsh/rpm_repo/lastrun
        keypath: None

    main-tools:
      schema: rpm
      host:
        schema: http://
        name: vdo-image-store.permabit.lab.eng.bos.redhat.com
        path: /eng-main-repo/RPMs
        keypath: None

    permatest:
      schema: rpm
      host:
        schema: http://
        name: vdo-image-store.permabit.lab.eng.bos.redhat.com
        path: /repository/permatest-repo
        keypath: None

    rh-cert:
      # To be removed (or nulled out) in published version.
      # Rely on a runtime determination to not attempt to access these.
      schema: uri
      host:
        schema: https://
        name: password.corp.redhat.com
        path: /RH-IT-Root-CA.crt
        keypath: None

    rsvpd:
      schema: rpm
      host:
        schema: http://
        name: coprbe.devel.redhat.com
        path: "/results/awalsh/TestVDOStaging/{{_distro_releasever}}-$basearch"
        keypath: /results/awalsh/TestVDOStaging/pubkey.gpg

  # Third party resources utilized.
  third-party:
    athinfo:
      schema: rpm
      host:
        schema: http://
        name: coprbe.devel.redhat.com
        path: "/results/VDO-team/StagingBunsenPackages/{{_distro_releasever}}-$basearch"
        keypath: /results/VDO-team/StagingBunsenPackages/pubkey.gpg

    scam:
      schema: rpm
      host:
        schema: http://
        name: coprbe.devel.redhat.com
        path: "/results/VDO-team/StagingBunsenPackages/{{_distro_releasever}}-$basearch"
        keypath: /results/VDO-team/StagingBunsenPackages/pubkey.gpg

    targetd:
      schema: rpm
      host:
        schema: https://
        name: coprbe.devel.redhat.com
        path: "/results/VDO-team/StagingBunsenPackages/{{_distro_releasever}}-$basearch"
        keypath: /results/VDO-team/StagingBunsenPackages/pubkey.gpg
