# Storage server variables.
---
_server_selection:
  distribution: "{{ ansible_distribution + ansible_distribution_version }}"
  architecture: "{{ ansible_machine }}"
  environment:

# Server packages.
_server_packages:
  # Common to all distributions.
  - common:
    - targetd

server_packages: "{{ _server_packages | select_install(_server_selection) }}"
